language: python
python:
 - "2.7"
before_install:
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  # Update packages repositories & install build tools
  - sudo apt-get update
  - sudo apt-get -y install subversion pbuilder debootstrap devscripts debian-archive-keyring dos2unix
  # Create a pbuilder chroot
  - sudo pbuilder create --distribution wheezy --debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg" --mirror http://httpredir.debian.org/debian/
  # Before building, add a hook to run lintian and add backports mirrors
  - sudo mkdir ~/pbuilderhooks
  - sudo cp /usr/share/doc/pbuilder/examples/B90lintian $HOME/pbuilderhooks
  - sudo -E sh -c "echo \"HOOKDIR=$HOME/pbuilderhooks/\" >> ~/.pbuilderrc"
  - sudo -E sh -c "echo 'OTHERMIRROR=\"deb http://httpredir.debian.org/debian wheezy-backports main\"' >> ~/.pbuilderrc"
  # Make sure get-orig-source works
  - sudo debian/rules get-orig-source
  # Move sources to proper place
  - sudo mv cutycapt*.tar.gz ~/amontalban
install:
  # Build the package
  - sudo pdebuild
deploy:
  provider: packagecloud
  repository: "amontalban/cutycapt"
  username: "amontalban"
  dist: "debian/wheezy"
